// Importing built-in dependencies
import type { Metadata } from 'next';
import Link from 'next/link';

// Importing components
import SessionWrapper from '@/components/sessionWrapper/sessionWrapper';
import ProtectedPage from '@/components/protectedPage/protectedPage';
import UserDropdown from '@/components/ui/dropdownMenu/dropdownMenu';
import { NavItem } from '@/components/ui/navItem/navItem';

import { HomeIcon, CubeIcon } from '@radix-ui/react-icons'

//const inter = Inter({ subsets: ['latin'] })
//import { Inter } from 'next/font/google'
//import './globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function AdminLayout({ children }: { children: React.ReactNode }) {
    return (
        <SessionWrapper>
            {/* <ProtectedPage> */}
                <main className="flex min-h-screen w-full flex-col bg-muted/40">
                    <DesktopNav />
                    <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
                        <header className="sticky top-0 z-30 flex h-14 items-center justify-end gap-4 border-b bg-background px-4 sm:static sm:h-auto sm:border-0 sm:bg-transparent sm:px-6">
                            {/* <MobileNav /> */}
                            <input type="text" />
                            <UserDropdown/>
                        </header>
                        <main className="grid flex-1 items-start gap-2 p-4 sm:px-6 sm:py-0 md:gap-4 bg-muted/40">
                            {children}
                        </main>
                    </div>
                </main>
            {/* </ProtectedPage> */}
        </SessionWrapper>
    )
}

function DesktopNav() {
    return (
      <aside className="fixed inset-y-0 left-0 z-10 hidden w-14 flex-col border-r bg-background sm:flex border-[var(--border)]">
        <nav className="flex flex-col items-center gap-4 px-2 sm:py-5">
          <Link
            href="https://vercel.com/templates/next.js/admin-dashboard-tailwind-postgres-react-nextjs"
            className="group flex h-9 w-9 shrink-0 items-center justify-center gap-2 rounded-full bg-primary text-lg font-semibold text-primary-foreground md:h-8 md:w-8 md:text-base"
          >
            {/* <VercelLogo className="h-3 w-3 transition-all group-hover:scale-110" /> */}
            <span className="sr-only">Acme Inc</span>
          </Link>
  
          <NavItem href="" label="Dashboard">
            <HomeIcon className="h-5 w-5" /> 
          </NavItem>
  
          <NavItem href="/admin/products" label="Products">
            <CubeIcon className="h-5 w-5" />
          </NavItem>
        </nav>

        <nav className="mt-auto flex flex-col items-center gap-4 px-2 sm:py-5">
          {/* <Tooltip>
            <TooltipTrigger asChild>
              <Link
                href="#"
                className="flex h-9 w-9 items-center justify-center rounded-lg text-muted-foreground transition-colors hover:text-foreground md:h-8 md:w-8"
              >
                <Settings className="h-5 w-5" />
                <span className="sr-only">Settings</span>
              </Link>
            </TooltipTrigger>
            <TooltipContent side="right">Settings</TooltipContent>
          </Tooltip> */}
        </nav>
      </aside>
    );
  }